local packer = require('packer')
local use = packer.use
packUse = use
return packer.startup({
    function()
        use("wbthomason/packer.nvim")  -- packer controls itself
        -- require("pluginSettings.lush").loadPlugin()
        require("pluginSettings.nvim-treesitter-context").loadPlugin()
        require("pluginSettings.lsp_signature").loadPlugin()
        require("pluginSettings.nvim-lightbulb").loadPlugin()
        require("pluginSettings.lualine").loadPlugin()
        require("pluginSettings.vim-surround").loadPlugin()
        require("pluginSettings.vim-repeat").loadPlugin()
        require("pluginSettings.lightspeed").loadPlugin()
        require("pluginSettings.nvim-treesitter").loadPlugin()
        require("pluginSettings.lsp-config").loadPlugin()
        require("pluginSettings.nvim-lsp-installer").loadPlugin()
        require("pluginSettings.lspkind-nvim").loadPlugin()
        require("pluginSettings.nvim-cmp").loadPlugin()
        require("pluginSettings.comment").loadPlugin()
        require("pluginSettings.nvim-ts-context-commentstring").loadPlugin()
        require("pluginSettings.indent-blankline").loadPlugin()
        require("pluginSettings.refactoring").loadPlugin()
        require("pluginSettings.nvim-autopairs").loadPlugin()
        require("pluginSettings.symbols-outline").loadPlugin()
        require("pluginSettings.nvim-dap-python").loadPlugin()
        require("pluginSettings.tabset").loadPlugin()
        require("pluginSettings.nvim-dap-ui").loadPlugin()
        require("pluginSettings.telescope-packer").loadPlugin()
        require("pluginSettings.nvim-dap-virtual-text").loadPlugin()
        require("pluginSettings.telescope").loadPlugin()
        require("pluginSettings.nvim-dap").loadPlugin()
        require("pluginSettings.trouble").loadPlugin()
        require("pluginSettings.nvim-lint").loadPlugin()
        require("pluginSettings.which-key").loadPlugin()
        require("pluginSettings.mapx").loadPlugin()
        require("pluginSettings.vim-indent-object").loadPlugin()

    end
})

